-- ============================================================
-- NotiMarket – Supabase SQL Schema
-- Run this in: Supabase Dashboard → SQL Editor → Run
-- ============================================================

-- ─── Extensions ────────────────────────────────────────────
create extension if not exists "uuid-ossp";

-- ─── News table ─────────────────────────────────────────────
-- Stores all news items fetched by the Node API (notimarket-api-node)
create table if not exists public.news (
  id           text        primary key,
  title        text        not null,
  summary      text,
  source       text,
  published_at timestamptz,
  url          text        not null unique,
  sentiment    text        not null default 'neutral',
  topic        text        not null default 'politica',
  fetched_at   timestamptz not null default now()
);

comment on table public.news is 'News items fetched from the upstream news-intelligence-api';

-- ─── Polls table ─────────────────────────────────────────────
-- Stores polls generated by the bot from news items
create table if not exists public.polls (
  id           text        primary key,
  news_id      text        references public.news(id) on delete set null,
  news_title   text        not null,
  news_url     text        not null,
  news_source  text,
  question     text        not null,
  options      jsonb       not null,   -- Array of { id, text, votes }
  topic        text        not null,
  sentiment    text        not null,
  province     text,                   -- DR province code (e.g. 'SDQ', 'STI')
  total_votes  integer     not null default 0,
  created_at   timestamptz not null default now(),
  created_by   uuid        references auth.users(id) on delete set null
);

comment on table public.polls is 'Polls generated from news items by the NotiMarket bot';

-- ─── Votes table ─────────────────────────────────────────────
-- One vote per user per poll
create table if not exists public.votes (
  id           uuid        primary key default gen_random_uuid(),
  poll_id      text        not null references public.polls(id) on delete cascade,
  user_id      uuid        not null references auth.users(id) on delete cascade,
  option_id    text        not null,
  option_index integer     not null,
  created_at   timestamptz not null default now(),
  unique (poll_id, user_id)
);

comment on table public.votes is 'User votes – one per poll per authenticated user';

-- ─── Row Level Security ──────────────────────────────────────
alter table public.news   enable row level security;
alter table public.polls  enable row level security;
alter table public.votes  enable row level security;

-- News: public read, service role write (backend upserts via service key)
create policy "News: public read"
  on public.news for select using (true);

-- Polls: public read, authenticated users can insert
create policy "Polls: public read"
  on public.polls for select using (true);

create policy "Polls: authenticated insert"
  on public.polls for insert
  with check (auth.uid() is not null);

-- Votes: users see own votes, can insert own votes
create policy "Votes: user reads own"
  on public.votes for select
  using (auth.uid() = user_id);

create policy "Votes: user inserts own"
  on public.votes for insert
  with check (auth.uid() = user_id);

-- ─── Indexes ─────────────────────────────────────────────────
create index if not exists news_topic_idx       on public.news  (topic);
create index if not exists news_fetched_at_idx  on public.news  (fetched_at desc);
create index if not exists polls_topic_idx      on public.polls (topic);
create index if not exists polls_province_idx   on public.polls (province);
create index if not exists polls_created_at_idx on public.polls (created_at desc);
create index if not exists votes_poll_id_idx    on public.votes (poll_id);
create index if not exists votes_user_id_idx    on public.votes (user_id);

-- ─── Profiles table ──────────────────────────────────────────
-- One row per user; created automatically via trigger on signup
create table if not exists public.profiles (
  id          uuid        primary key references auth.users(id) on delete cascade,
  full_name   text,
  avatar_url  text,
  role        text        not null default 'user' check (role in ('user', 'admin')),
  created_at  timestamptz not null default now()
);

comment on table public.profiles is 'User profiles with roles (user | admin)';

-- ─── Helper function (avoids RLS recursion) ──────────────────
create or replace function public.is_admin()
returns boolean as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$ language sql security definer stable;

-- ─── Trigger: auto-create profile on signup ──────────────────
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─── Profiles RLS ────────────────────────────────────────────
alter table public.profiles enable row level security;

create policy "Profiles: authenticated read"
  on public.profiles for select
  using (auth.uid() is not null);

create policy "Profiles: insert own"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Profiles: user updates own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (role = (select role from public.profiles where id = auth.uid()));

create policy "Profiles: admin updates any"
  on public.profiles for update
  using (public.is_admin());

create index if not exists profiles_role_idx on public.profiles (role);

-- ─── Google OAuth ────────────────────────────────────────────
-- Enable in: Supabase Dashboard → Authentication → Providers → Google
-- You need: Client ID + Client Secret from Google Cloud Console
-- Callback URL: https://<your-project>.supabase.co/auth/v1/callback

-- ─── Poll Accesses table ─────────────────────────────────────
-- Tracks QR code scans with IP-based geolocation (privacy-safe)
create table if not exists public.poll_accesses (
  id          uuid        primary key default gen_random_uuid(),
  poll_id     text        not null references public.polls(id) on delete cascade,
  lat         numeric(9,6),
  lng         numeric(9,6),
  province    text,
  city        text,
  ip_hash     text,                   -- First 3 octets of IP (e.g. "190.22.14")
  ref         text        not null default 'direct'
                          check (ref in ('qr', 'direct')),
  created_at  timestamptz not null default now()
);

comment on table public.poll_accesses is 'QR scan events with geolocation for heatmap analytics';

alter table public.poll_accesses enable row level security;

-- Anyone (including anonymous) can insert when scanning a QR
create policy "PollAccesses: anon insert"
  on public.poll_accesses for insert
  with check (true);

-- Only admins can read scan analytics
create policy "PollAccesses: admin select"
  on public.poll_accesses for select
  using (public.is_admin());

create index if not exists poll_accesses_poll_id_idx    on public.poll_accesses (poll_id);
create index if not exists poll_accesses_province_idx   on public.poll_accesses (province);
create index if not exists poll_accesses_created_at_idx on public.poll_accesses (created_at desc);

-- ─── News Sources ────────────────────────────────────────────
-- Configurable news sites the bot scrapes for articles
create table if not exists public.news_sources (
  id         uuid        primary key default gen_random_uuid(),
  url        text        not null unique,
  name       text        not null,
  rss_url    text,
  enabled    boolean     not null default true,
  created_at timestamptz not null default now(),
  created_by uuid        references auth.users(id) on delete set null
);

comment on table public.news_sources is 'Configurable news sites for bot article scraping';

alter table public.news_sources enable row level security;

create policy "Sources: admin all"
  on public.news_sources
  using (public.is_admin()) with check (public.is_admin());

create policy "Sources: public read enabled"
  on public.news_sources for select
  using (enabled = true);

create index if not exists news_sources_enabled_idx on public.news_sources(enabled);

-- ─── Social links column on polls ────────────────────────────
-- Stores { twitter?: url, facebook?: url, tiktok?: url }
alter table public.polls
  add column if not exists social_links jsonb;

-- ─── Social Comments Cache ────────────────────────────────────
-- Cached comments fetched from Twitter/Facebook/TikTok per poll
create table if not exists public.social_comments (
  id            uuid        primary key default gen_random_uuid(),
  poll_id       text        not null references public.polls(id) on delete cascade,
  platform      text        not null check (platform in ('twitter','facebook','instagram','tiktok')),
  comment_id    text        not null,
  author_name   text,
  author_handle text,
  text          text,
  likes         integer     not null default 0,
  reply_count   integer     not null default 0,
  is_bot        boolean,
  bot_score     numeric(3,2),
  fetched_at    timestamptz not null default now(),
  unique (platform, comment_id)
);

comment on table public.social_comments is 'Cached social media comments with bot detection scores';

alter table public.social_comments enable row level security;

create policy "SocialComments: admin all"
  on public.social_comments
  using (public.is_admin()) with check (public.is_admin());

create policy "SocialComments: public read"
  on public.social_comments for select using (true);

create index if not exists social_comments_poll_id_idx on public.social_comments(poll_id);
create index if not exists social_comments_platform_idx on public.social_comments(platform);

-- ─── Cómo otorgarte rol admin (primera vez) ──────────────────
-- Corre esto en Supabase Dashboard → SQL Editor:
--
-- update public.profiles
--   set role = 'admin'
--   where id = (select id from auth.users where email = 'tu@email.com');
--
-- Después de eso, el Panel Admin estará habilitado en la UI.

-- ─── Bot Configs ──────────────────────────────────────────────
-- One row per admin user – stores bot settings persistently.
create table if not exists public.bot_configs (
  id               uuid        primary key default gen_random_uuid(),
  user_id          uuid        not null unique references auth.users(id) on delete cascade,
  enabled          boolean     not null default false,
  llm_provider     text        not null default 'mock'
                               check (llm_provider in ('mock','openai','gemini','openrouter')),
  llm_api_key      text,                -- stored as-is; encrypt at rest via Supabase Vault in production
  openrouter_model text        not null default 'openai/gpt-4o-mini',
  topic            text        not null default 'politica',
  interval_minutes integer     not null default 60 check (interval_minutes >= 1),
  asset_id         text,
  updated_at       timestamptz not null default now()
);

comment on table public.bot_configs is 'Per-user bot configuration, one row per admin';

alter table public.bot_configs enable row level security;

-- User can read/write their own config only
create policy "BotConfigs: user read own"
  on public.bot_configs for select
  using (auth.uid() = user_id);

create policy "BotConfigs: user insert own"
  on public.bot_configs for insert
  with check (auth.uid() = user_id);

create policy "BotConfigs: user update own"
  on public.bot_configs for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "BotConfigs: user delete own"
  on public.bot_configs for delete
  using (auth.uid() = user_id);

-- ============================================================
-- SURVEYS – Admin-created multi-question polls
-- This block is self-contained: run it independently if needed.
-- ============================================================

-- ─── Ensure is_admin() helper exists (idempotent) ────────────────────────────
-- Checks if the current authenticated user has role='admin' in public.profiles.
create or replace function public.is_admin()
returns boolean as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$ language sql security definer stable;

-- ─── Surveys table ────────────────────────────────────────────────────────────
create table if not exists public.surveys (
  id               uuid        primary key default gen_random_uuid(),
  title            text        not null,
  description      text,
  topic            text        not null default 'política',
  province         text,
  status           text        not null default 'active'
                               check (status in ('active', 'closed', 'draft')),
  questions        jsonb       not null default '[]',
  -- questions: [{id, question, options: [{id, text}]}]  ← no votes here, use get_survey_results()
  total_responses  integer     not null default 0,
  created_by       uuid        references auth.users(id) on delete set null,
  created_at       timestamptz not null default now()
);

comment on table public.surveys is 'Admin-created surveys with multiple questions stored as JSONB';

alter table public.surveys enable row level security;

create policy "Surveys: public read active"
  on public.surveys for select
  using (status = 'active' or public.is_admin());

create policy "Surveys: admin insert"
  on public.surveys for insert
  with check (public.is_admin());

create policy "Surveys: admin update"
  on public.surveys for update
  using (public.is_admin())
  with check (public.is_admin());

create policy "Surveys: admin delete"
  on public.surveys for delete
  using (public.is_admin());

create index if not exists surveys_status_idx     on public.surveys (status);
create index if not exists surveys_created_at_idx on public.surveys (created_at desc);

-- ─── Survey Responses table ───────────────────────────────────────────────────
create table if not exists public.survey_responses (
  id             uuid        primary key default gen_random_uuid(),
  survey_id      uuid        not null references public.surveys(id) on delete cascade,
  user_id        uuid        not null references auth.users(id) on delete cascade,
  answers        jsonb       not null,
  -- answers: [{question_id, option_id, option_index}]
  province       text,
  captcha_score  numeric(3,2),   -- reCAPTCHA v3 score (0.0–1.0); null if not verified
  created_at     timestamptz not null default now(),
  unique (survey_id, user_id)    -- one submission per user per survey
);

comment on table public.survey_responses is 'User responses to surveys – one row per user per survey';

alter table public.survey_responses enable row level security;

create policy "SurveyResp: user insert own"
  on public.survey_responses for insert
  with check (auth.uid() = user_id);

create policy "SurveyResp: user reads own"
  on public.survey_responses for select
  using (auth.uid() = user_id or public.is_admin());

-- No UPDATE policy – responses are immutable once submitted

create index if not exists survey_resp_survey_idx on public.survey_responses (survey_id);
create index if not exists survey_resp_user_idx   on public.survey_responses (user_id);

-- ─── Trigger: increment total_responses only ─────────────────────────────────
-- Votes are NOT tallied into questions JSONB.
-- Use get_survey_results() RPC for per-option counts.
create or replace function public.handle_new_survey_response()
returns trigger as $$
begin
  update public.surveys
    set total_responses = total_responses + 1
    where id = new.survey_id;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_survey_response_created on public.survey_responses;
create trigger on_survey_response_created
  after insert on public.survey_responses
  for each row execute procedure public.handle_new_survey_response();

-- ─── RPC: get_survey_results ─────────────────────────────────────────────────
-- Returns aggregated vote counts per option for a given survey.
-- Security definer: any authenticated user gets totals without seeing individual rows.
create or replace function public.get_survey_results(p_survey_id uuid)
returns table(question_id text, option_id text, vote_count bigint)
language sql security definer stable as $$
  select
    a->>'question_id' as question_id,
    a->>'option_id'   as option_id,
    count(*)          as vote_count
  from public.survey_responses,
       lateral jsonb_array_elements(answers) as a
  where survey_id = p_survey_id
  group by a->>'question_id', a->>'option_id';
$$;

create index if not exists bot_configs_user_id_idx on public.bot_configs (user_id);
